export const LOAD_MENU = "LOAD_MENU"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CALK_TOTAL_PRICE = "CALK_TOTAL_PRICE"
export const CONFIRM_ORDER = "CONFIRM_ORDER"
export const LOAD_ORDER_STORY = "LOAD_ORDER_STORY"
export const SIZE_CHOICE = 'SIZE_CHOICE'
